path:
  processed_path: "data/processed/energy_features.csv"
  output_dir: "models"

datetime_column: "Datetime"
target: "PJME_MW"
train_end: "2014-01-01"

features:
  columns:
    - dayofyear
    - hour
    - dayofweek
    - quarter
    - month
    - year
    - lag_364d
    - lag_728d
    - lag_1092d

model:
  name: "xgboost"
  booster: "gbtree"
  n_estimators: 1000
  max_depth: 3
  learning_rate: 0.01
  base_score: 0.5
  objective: "reg:squarederror"

cv:
  n_splits: 5
  test_size: 8760
  gap: 24

seed: 42
